# Generated by Django 6.1 on 2026-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
